name: Deploy React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      # Optional: Upload build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
